hashkey = {
    "a": "d&-M8tOD7nCYS",
    "b": "{yi6=2r}Wx@n3:gU-DLQ",
    "c": "5=rhZ0Hb>I/,e<",
    "d": "@'i!R$1",
    "e": "*I|MKl%N09Rc(E'ze,",
    "f": "S(a+W_Ao.uEFzUT5",
    "g": "`PsQ}9)Bm#fk4v]cJ^",
    "h": "!.HqJ_kh48F~p",
    "i": "$abuo]Tj#5Pv)^dSVm+",
    "j": "wA`/fXs&[<7GtO?Z1YB>C",
    "k": "b>I/,e<G",
    "l": "zUT5=rhZ0Hb>I/,e<Gx26",
    "m": "D7nCYS(a+W_Ao",
    "n": "d&-M8tOD7nCYS(a+W",
    "o": "T5=rhZ0Hb>I/",
    "p": ">I/,e<Gx26pl~*N%[X3y",
    "q": "R$1j{g|Lq:`PsQ}9)Bm#fk4",
    "r": "Kl%N0",
    "s": "wA`/fXs&[<7G",
    "t": "_kh48F~p",
    "u": "{yi6=2r}Wx",
    "v": "(a+W_Ao.uEFzUT5=",
    "w": "{yi6=2r}Wx@n3",
    "x": "-M8tOD7nCYS(a+W",
    "y": "/fXs&[<",
    "z": "l~*N%[X3ywVK?@'i",
    "A": "k4v]cJ^",
    "B": "Z0Hb>I/,e<",
    "C": "Ao.uEFzUT5=rhZ0Hb>I/,e<",
    "D": "2r}Wx@n3:gU-D",
    "E": "wA`/fXs&[",
    "F": "kh48F~p",
    "G": "Xs&[<7GtO?Z1YB>C",
    "H": "$abuo]Tj#5P",
    "I": "a+W_Ao.uEFzUT5=rhZ0Hb>I/",
    "J": "pl~*N%[X3ywVK?@",
    "K": "ywVK?@'i!R$1j{g|Lq:`PsQ}9)Bm",
    "L": "d&-M8tOD7nC",
    "M": "+W_",
    "N": "@n3:gU-DL",
    "O": "nCYS(a+W_Ao.uEFzUT5",
    "P": "x26pl~*N%[X3",
    "Q": "=2r}Wx@n",
    "R": "MKl%N0",
    "S": "s&[<7Gt",
    "T": "{yi6=2r}Wx",
    "U": "/fXs&[<7",
    "V": "J_kh48F~p",
    "W": "GtO?Z1YB>C",
    "X": "5Pv)^dSVm+",
    "Y": ")Bm#fk4v]cJ^",
    "Z": "e<Gx26pl~*",
    "1": "OD7nCYS(a+",
    "2": "uEFzUT5=rhZ0Hb>I/,e<",
    "3": "[X3ywVK?@'",
    "4": "&-M8tOD7",
    "5": "UT5=rhZ0Hb>I/",
    "6": "Gx26pl~*N%[X3y",
    "7": "5Pv)^dSVm+",
    "8": "J_kh48F~p",
    "9": "*I|MKl%",
    "0": "&-M8tOD7n",
    "~": ".uEFzUT5=rhZ0Hb>I/",
    "`": "3ywVK?@'i!R$",
    "!": "D7nCYS(a+W_Ao",
    "@": "K?@'i!R$1j{g|Lq:`",
    "#": "+W_Ao.uEFzU",
    "$": "'i!R$1j{g|Lq:`",
    "%": "v)^dSVm+",
    "^": "_kh48F~p",
    "&": "5Pv)^dSVm+",
    "*": "{yi6=2r}W",
    "(": "9Rc(E'ze,",
    ")": "qJ_kh48F",
    "_": "a+W_Ao.uEFzUT5=",
    "-": "b>I/,e<Gx26pl~*N%",
    "+": "d&-M8tOD7nC",
    "=": "#5Pv)^dSVm+",
    "{": "qJ_kh48F~p",
    "[": "7GtO?Z1YB>C",
    "}": "MKl%N09R",
    "]": "a+W_Ao.uEFzUT",
    "|": "abuo]Tj#",
    ":": "i6=2r}Wx@n",
    "'": "7GtO?Z1YB>",
    "<": "l%N09Rc(E'",
    ",": "Ao.uEFzUT5=rhZ0Hb>I/",
    ">": "@'i!R$1j{g|Lq:`P",
    ".": "x@n3:gU-D",
    "?": "&[<7GtO?Z1YB",
    "/": "2r}Wx@n"
}
#characters
#ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~`!@#$%^&*()_-+={[}]|:'<,>.?/


def hash(word):
    word_length = len(word)
    hashed = ""
    for x in range(word_length):
        hashed += hashkey[word[x]]
    return hashed
