hashkey = {
    "a": "asda",
    "b": "as",
    "c": "dsad",
    "d": "sdasad",
    "e": "asdasd",
    "f": "ssdada",
    "g": "asdasd",
    "h": "ssadwas",
    "i": "wadsda",
    "j": "wadsdasdw",
    "k": "sada",
    "l": "asd",
    "m": "dwad",
    "n": "dwadsa",
    "o": "dwadas",
    "p": "a",
    "q": "s",
    "r": "wdadwa",
    "s": "d",
    "t": "dwadawdawd",
    "u": "awdad",
    "v": "wd",
    "w": "w",
    "x": "dawd",
    "y": "adawda",
    "z": "dwadawd",
    "A": "sadawdas",
    "B": "wadsa",
    "C": "wad",
    "D": "wadwa",
    "E": "awdwas",
    "F": "wadsaa",
    "G": "awdwa",
    "H": "wdada",
    "I": "sadaw",
    "J": "sad",
    "K": "saasddaw",
    "L": "sadwa",
    "M": "aasdaw",
    "N": "sdawd",
    "O": "asdwa",
    "P": "sdawd",
    "Q": "dawsd",
    "R": "wadawda",
    "S": "awdad",
    "T": "dawdasdw",
    "U": "w",
    "V": "dwadasd",
    "W": "sdadwa",
    "X": "dwadsaadawd",
    "Y": "dwadasdaw",
    "Z": "wadawd",
    "1": "sdsad",
    "2": "sdad",
    "3": "sadwad",
    "4": "dawdasd",
    "5": "sadawd",
    "6": "sadawdawd",
    "7": "sadadswa",
    "8": "sadawd",
    "9": "dwadawd",
    "0": "sadawd",
}

def hash(key):
    word_length = len(key)
    hashed = ""
    for x in range(word_length):
        hashed += hashkey[key[x]]
    return hashed
